title: Maitreya Kulkarni
logo: /assets/img/mk.png
email: maitreyakr@gmail.com mkulk98@umd.edu
description: Minimalist is a theme powered by Jekyll. It is modified based on the Minimal theme.
show_downloads: false
google_analytics: UA-108144808-1
theme: jekyll-theme-minimalist
color-scheme: dark
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
