title: Maitreya Kulkarni
logo: /assets/img/mk.png
email: maitreyakr@gmail.com mkulk98@umd.edu
description: Graduate student at University of Maryland pursuing Masters in Robotics,intersted in autonomous and defense robotics.
show_downloads: false
google_analytics: UA-108144808-1
theme: jekyll-theme-minimalist
color-scheme: dark
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
